Update workflow.yaml

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -1,17 +1,31 @@
-on: [push]
+name: main
+on:
+  workflow_dispatch:
 
 jobs:
-  apply:
+  build:
+    name: build
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - name: Apply Terraform changes
-      run: |
-        # Set a timeout of 30 minutes for the terraform apply command
-        if timeout 1m sleep 30; then
-          echo "Terraform apply successful"
-        else
-          echo "Terraform apply failed or timed out"
-          exit 1
-        fi
+      - name: Build
+        run: echo building
+  deploy:
+    name: deploy
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: trstringer/manual-approval@v1
+        with:
+          secret: ${{ github.TOKEN }}
+          approvers: trstringer,acdunnigan
+      - name: Deploy to production
+        run: echo deploying
+      - name: Apply Terraform changes
+        run: |
+            if timeout 1m sleep 30; then
+              echo "Terraform apply successful"
+            else
+              echo "Terraform apply failed or timed out"
+              exit 1
+            fi
 
