Update workflow.yaml

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -1,15 +1,17 @@
-name: 'Workflow dispatch test'
-on: push
+on: [push]
+
 jobs:
-  testjob:
+  apply:
     runs-on: ubuntu-latest
     steps:
-      - name: Set environment variable
-        shell: bash
-        run: |
-              abc="hello"
-              export -p abc
-      - name: scdscasc
-        run: |
-           bbc=$abc
-           echo $bbc
+    - uses: actions/checkout@v2
+    - name: Apply Terraform changes
+      run: |
+        # Set a timeout of 30 minutes for the terraform apply command
+        if timeout 1m terraform apply; then
+          echo "Terraform apply successful"
+        else
+          echo "Terraform apply failed or timed out"
+          exit 1
+        fi
+
