Update workflow.yaml

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -1,28 +1,41 @@
-name: main
+name: My Workflow
+
 on: push
+
 jobs:
   build:
-    name: build
     runs-on: ubuntu-latest
     steps:
-      - name: Build
-        run: echo building manual review deny
-  deploy:
-    name: deploy
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: trstringer/manual-approval@v1
-        with:
-          secret: ${{ github.TOKEN }}
-          approvers: SuprajMaripeddi
-      - name: Deploy to production
-        run: echo deploying
-      - name: Apply Terraform changes
-        run: |
-            if timeout 5m sleep 30; then
-              echo "Terraform apply successful"
-            else
-              echo "Terraform apply failed or timed out"
-              exit 1
-            fi
+    - name: Run action
+      uses: ./.github/actions/my-action
+      with:
+        myInput: "Hello, world!"
+
+# name: main
+# on: push
+# jobs:
+#   build:
+#     name: build
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Build
+#         run: echo building manual review deny
+#   deploy:
+#     name: deploy
+#     runs-on: ubuntu-latest
+#     needs: build
+#     steps:
+#       - uses: trstringer/manual-approval@v1
+#         with:
+#           secret: ${{ github.TOKEN }}
+#           approvers: SuprajMaripeddi
+#       - name: Deploy to production
+#         run: echo deploying
+#       - name: Apply Terraform changes
+#         run: |
+#             if timeout 5m sleep 30; then
+#               echo "Terraform apply successful"
+#             else
+#               echo "Terraform apply failed or timed out"
+#               exit 1
+#             fi
